### ISSUE TITLE
THANK YOU VERY MUCH!

### ISSUE THREAD

**Issue by spkis** [IngmarStein/tcp-multiplexer#5]
Hey there,

I just wanted to save a HUGE THANK YOU TO YOU.
I have found this project because I was using modbus proxy. That did work however, it was not the most performant. I do BESS monitoring with well... a lot of data points per second :-) 
The modbus proxy does work fine, however at our bigger plants, it was eating up CPU a lot!

I just implemented your tcp-multiplexer now, and currently CPU load is close to not noticable! That is amazing!

To give you some feedback with data:
<img width="465" alt="image" src="https://github.com/user-attachments/assets/d260809d-c800-4510-ab07-8ace7613e5f8">

1. Starting of modbus_proxy containers.
2. Starting of tcp-multiplexer.

It's like 20 containers for proxy, 20 containers telegraf with multiple calls to the device through proxy and 20 containers for telling the BMS which racks to return to me every other second.  

So thanks for your efforts on this project! I will speak with my manager to see if we can send you some $$$ via Sponsor function :-)

**Comment by IngmarStein** [comment]
Oh wow, that‘s a large-scale deployment!
I‘m glad that you get good value out of the project. Please let me know if you encounter issues or have improvement suggestions.

**Comment by IngmarStein** [comment]
Alright, I'll close this issue as there's nothing actionable. Feel free to open new issues should you encounter problems.
Thanks again for the feedback!
