### ISSUE TITLE
Built for arch "arm" (RaspberryPi)

### ISSUE THREAD

**Issue by davidrahusen** [IngmarStein/tcp-multiplexer#6]
Interesting tool! Would be great, if it would be available for RaspberryPi as well. Any chance?

**Comment by IngmarStein** [comment]
No problem. I've just released v1.0.2 which includes an arm/v6 build, I hope that works for you.

**Comment by davidrahusen** [comment]
Woah, that is promptly. 😁 
My bad I wasn't precise enough ... 😞 I'm using a Raspberry Pi 3 Model B, which is an ARMv7, new models are ARMv8. Could you rebuild it for them as well?

**Comment by IngmarStein** [comment]
Ha, neither "arm" nor "Raspberry Pi" were precise enough, it seems :)
Please try v1.0.5 which comes in amd64, arm64, arm/v6, and arm/v7 flavors.
