### ISSUE TITLE
Are there plans for doing multiplexing in the other way?

### ISSUE THREAD

**Issue by PJ-Schulz** [IngmarStein/tcp-multiplexer#8]
I have a device that sends CANbus frames over TCP to a single client. 
The client connects to the server and receives the CANbus frames through the TCP stream. However, the device only accepts one connection at a time, but I need multiple clients to connect to the server. 

During my research I came across this project, but it doesn't quite cover what I need for my use case. Hence my question, are there any plans to implement such a usecase? Are people how have the same usecase?

**Comment by IngmarStein** [comment]
When you say "the device only accepts one connection at a time", I assume "device" means "server". That would be the exact use case of this project. It doesn't support the CAN bus protocol, however. I'd gladly accept a contribution.
