### ISSUE TITLE
node-red query error

### ISSUE THREAD

**Issue by MaGeHome** [IngmarStein/tcp-multiplexer#9]
Hello,

I am currently using the ioBroker with the node-red adapter to query my Huawei photovoltaic system. The Modbus TCP query is running stably without errors. 
I would like to change the query via the multiplexer. 

Unfortunately, I receive the following message in the log.

```
time="2024-11-17T22:19:49+01:00" level=info msg="#1: 172.18.0.1:33904 <-> 172.18.0.2:502"
time="2024-11-17T22:19:49+01:00" level=info msg="Connected clients: 1"
time="2024-11-17T22:19:51+01:00" level=info msg="creating target connection"
time="2024-11-17T22:19:51+01:00" level=info msg="new target connection: 172.18.0.2:34376 <-> 192.168.0.18:502"
time="2024-11-17T22:20:00+01:00" level=info msg="#2: 172.18.0.1:40410 <-> 172.18.0.2:502"
time="2024-11-17T22:20:12+01:00" level=info msg="#3: 172.18.0.1:56430 <-> 172.18.0.2:502"
time="2024-11-17T22:20:24+01:00" level=info msg="#4: 172.18.0.1:52962 <-> 172.18.0.2:502"
time="2024-11-17T22:20:36+01:00" level=info msg="#5: 172.18.0.1:47416 <-> 172.18.0.2:502"
time="2024-11-17T22:20:48+01:00" level=info msg="#6: 172.18.0.1:55528 <-> 172.18.0.2:502"
**time="2024-11-17T22:20:51+01:00" level=error msg="target connection: read tcp 172.18.0.2:34376->192.168.0.18:502: i/o timeout"
time="2024-11-17T22:20:51+01:00" level=error msg="failed to forward message, read tcp 172.18.0.2:34376->192.168.0.18:502: i/o timeout"**
time="2024-11-17T22:20:51+01:00" level=info msg="Connected clients: 2"
time="2024-11-17T22:20:51+01:00" level=info msg="creating target connection"
time="2024-11-17T22:20:52+01:00" level=info msg="new target connection: 172.18.0.2:38648 <-> 192.168.0.18:502"
time="2024-11-17T22:21:00+01:00" level=info msg="#7: 172.18.0.1:57906 <-> 172.18.0.2:502"
time="2024-11-17T22:21:12+01:00" level=info msg="#8: 172.18.0.1:54888 <-> 172.18.0.2:502"
time="2024-11-17T22:21:24+01:00" level=info msg="#9: 172.18.0.1:56190 <-> 172.18.0.2:502"
time="2024-11-17T22:21:36+01:00" level=info msg="#10: 172.18.0.1:36884 <-> 172.18.0.2:502"
time="2024-11-17T22:21:48+01:00" level=info msg="#11: 172.18.0.1:45178 <-> 172.18.0.2:502"
**time="2024-11-17T22:21:52+01:00" level=error msg="target connection: read tcp 172.18.0.2:38648->192.168.0.18:502: i/o timeout"
time="2024-11-17T22:21:52+01:00" level=error msg="failed to forward message, read tcp 172.18.0.2:38648->192.168.0.18:502: i/o timeout"**
```

In ioBroker I get the following message in the log.

**[error] [modbus-client:ModBus-TCP] Error: connect ENETUNREACH 172.18.0.2:502 at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)**

The multiplexer runs in a container on the same host.

```
services:
  modbus-proxy:
    platform: linux/arm64
    image: ghcr.io/ingmarstein/tcp-multiplexer
    container_name: Modbus-Multiplexer
    ports:
      - "502:502"
    command: [ "server", "-t", "192.168.0.18:502", "-l", "502", "-p", "modbus", "-v" ]
    restart: always
    environment:
      TZ: Europe/Berlin
    hostname: Modbus_Container
    dns: 192.168.0.1
```

I am not sure what the problem could be and would be happy for help

Regards

**Comment by IngmarStein** [comment]
There are two things to try out:
- listen on a non-privileged port (e.g. 1502) inside the container
- check network connectivity to the inverter using a different container, for example `docker run --rm alpine ping 192.168.0.18`

**Comment by MaGeHome** [comment]
Thanks for your help.

I checked the network connectivity. 
The connection is good.
```
$ docker run --rm alpine ping 192.168.0.18
PING 192.168.0.18 (192.168.0.18): 56 data bytes
64 bytes from 192.168.0.18: seq=0 ttl=254 time=0.699 ms
64 bytes from 192.168.0.18: seq=1 ttl=254 time=0.308 ms
64 bytes from 192.168.0.18: seq=2 ttl=254 time=0.418 ms
64 bytes from 192.168.0.18: seq=3 ttl=254 time=0.300 ms
--- 192.168.0.18 ping statistics ---
4 packets transmitted, 4 packets received, 0% packet loss
round-trip min/avg/max = 0.300/0.431/0.699 ms
``` 
```
$ docker run --rm alpine ping 192.168.0.18:502
PING 192.168.0.18:502 (192.168.0.18): 56 data bytes
64 bytes from 192.168.0.18: seq=0 ttl=254 time=0.595 ms
64 bytes from 192.168.0.18: seq=1 ttl=254 time=0.301 ms
64 bytes from 192.168.0.18: seq=2 ttl=254 time=0.289 ms
64 bytes from 192.168.0.18: seq=3 ttl=254 time=0.311 ms
--- 192.168.0.18:502 ping statistics ---
4 packets transmitted, 4 packets received, 0% packet loss
round-trip min/avg/max = 0.289/0.374/0.595 ms
```

I changed the Port inside the container to 1502.
Unfortunately this does not bring any change.

```
services:
  modbus-proxy:
    platform: linux/arm64
    image: ghcr.io/ingmarstein/tcp-multiplexer
    container_name: Modbus-Multiplexer
    ports:
      - "1502:502"
    command: [ "server", "-t", "192.168.0.18:502", "-l", "502", "-p", "modbus", "-v" ]
    restart: always
    environment:
      TZ: Europe/Berlin
    hostname: Modbus_Container
    dns: 192.168.0.1
```

The host runs on 192.168.0.29, node-red on port 1880 and the ioBroker on port 8081. Is it possible that additional port shares are required for forwarding the message in the container?

Regards

**Comment by IngmarStein** [comment]
The modified Compose file changed the exposed port, not the listening port. Try this:

```
services:
  modbus-proxy:
    platform: linux/arm64
    image: ghcr.io/ingmarstein/tcp-multiplexer
    container_name: Modbus-Multiplexer
    ports:
      - "502:1502"
    command: [ "server", "-t", "192.168.0.18:502", "-l", "1502", "-p", "modbus", "-v" ]
    restart: always
    environment:
      TZ: Europe/Berlin
    hostname: Modbus_Container
    dns: 192.168.0.1
```

**Comment by IngmarStein** [comment]
Looking a bit more into the log, it looks like network connectivity isn't the problem. Both the connections from the client to the multiplexer and from the multiplexer to the inverter work. Five messages are exchanged successfully, but the sixth message causes the multiplexer to wait for a response from the inverter which isn't fully read within 60 seconds.

It could be an issue with the modbus implementation or quirk for this inverter model. Can you add `-d` to the command line and try again?

**Comment by MaGeHome** [comment]
I added ```-d``` to the command line.
```
command: [ "server", "-t", "192.168.0.18:502", "-l", "1502", "-p", "modbus", "-v", "-d" ]
```
I have also changed the query interval from 10s to 60s in node-red.
Unfortunately, this has no effect.

The multiplexer only shows me connected in node-red. (see far right under iob write value boxes)
![grafik](https://github.com/user-attachments/assets/04e91d1c-8b0b-404d-9db0-c26576d73308)

In the query without multiplexer, the values are displayed directly after a second.
So I think that the queries are sent. But the answers do not come back
![grafik](https://github.com/user-attachments/assets/4dd28ac8-ff5e-49ee-a1b6-fb70c4a1df6f)

Thanks for your help.

**Comment by IngmarStein** [comment]
Oh yeah, `-d` just enables debug mode. I'd be interested in the log output.

I don't use node-red and the flow charts and the config files are not needed to debug the issue.

**Comment by MaGeHome** [comment]
Even if I'm embarrassing myself now. :-) Where does the container store the debug log?
In Portainer I only see this LogPath.
```
LogPath /var/lib/docker/containers/afb9e191f6da38e10f97c7dbc7cb4d2154907c366bd860fa7911ce83edfe1cf2/afb9e191f6da38e10f97c7dbc7cb4d2154907c366bd860fa7911ce83edfe1cf2-json.log
```
And there is only the same content that I have already shown.

**Comment by MaGeHome** [comment]
Correct, the Modbus of the inverter only allows one connection. I therefore disconnect the connection to node-red before connecting the multiplexer. Otherwise the multiplexer would return connection denied.

I have not used Wireshark yet. I'll have a look at it.

**Comment by capi** [comment]
Make sure that your server at 192.168.0.18 doesn't have any iptables (or other firewall) rules that prevent speaking to it from inside a docker container. I fell into this trap once that a port was accessible from my network 192.168.0.0/24 since I whitelisted the netmask, but I forgot that the container was a) not connecting via eth0 but the bridge interface and b) in a 172.28.0.0/24 subnet.

Try, if you can get it working by using `network_mode: host` which means that the container will run in the network stack of the Docker host. If this works, you really likely have firewalling and/or NAT issues somewhere.

**Comment by MaGeHome** [comment]
> Make sure that your server at 192.168.0.18 doesn't have any iptables (or other firewall) rules that prevent speaking to it from inside a docker container. I fell into this trap once that a port was accessible from my network 192.168.0.0/24 since I whitelisted the netmask, but I forgot that the container was a) not connecting via eth0 but the bridge interface and b) in a 172.28.0.0/24 subnet. (This should be relevant only if 192.168.0.18 is actually also your docker host.)
> 
> Try, if you can get it working by using `network_mode: host` which means that the container will run in the network stack of the Docker host. If this works, you really likely have firewalling and/or NAT issues somewhere.
> 
> Edit: If 192.168.0.18 is actually your docker-host, you might need to expose access to the host like the following:
> 
> ```
> extra_hosts:
>       - "host.docker.internal:host-gateway"
> ```
> 
> And then you need to connect to host.docker.internal instead of 192.168.0.28

Thank you for your help and advice.
192.168.0.18 is not my Docker host. My Docker host is 192.168.0.29. My Docker host itself does not have its own firewall.

I have changed the container's network to host. Unfortunately, the result is unchanged.

**Comment by MaGeHome** [comment]
I have installed Wireshark on my host and added Edgeshark in a container. I have also added the cshargextcap package.
Here is the overview from Edgeshark.
![edgeshark-20241102-193143](https://github.com/user-attachments/assets/8704a605-3c4e-4f14-b0c7-24438ba1b625)

Unfortunately, I have not yet managed to get a connection to the Multilpexer Conatiner to record the traffic.
![grafik](https://github.com/user-attachments/assets/b25d3ae8-7210-461b-9705-7da09c765eeb)

**Comment by MaGeHome** [comment]
I stopped the node-red flow before each start and only then started the multiplexer container. 
Accordingly, I would say that I only have a connection to the inverter when operating the multiplexer.

Here is the recording file from Wireshark. I have attached the file as a zip, as the pcapng format is not accepted.
[Mitschnittdatei_Wireshark.zip](https://github.com/user-attachments/files/17821396/Mitschnittdatei_Wireshark.zip)

I am very grateful for your help.
Unfortunately, I am reaching the limits of my knowledge in this matter.

**Comment by IngmarStein** [comment]
I can't see a problem with tcp-multiplexer in this trace.

In frame 6, node-red sends a modbus message to the multiplexer: `00 01 00 00 00 06 01 03 7d 10 00 7c` (Transaction Identifier: 1, Protocol Identifier: 0, Length: 6, Unit Identifier: 1, Function Code: Read Holding Registers (3), Reference Number: 32016, Word Count: 124)
 
In frame 11, the multiplexer sends the exact same message to the inverter (192.168.0.18). The only difference in the frame is that the TCP connection from the multiplexer doesn't include the TCP timestamp option and that shouldn't matter.

In the following trace, the inverter only sends TCP keepalive frames (e.g. frames 24, 43, …).
Eventually, the multiplexer stops waiting.

Does the request take very long? The multiplexer has a fixed timeout of 60 seconds.

**Comment by IngmarStein** [comment]
In case it just is a very slow operation: 1.0.6 adds a `--timeout` flag which you could use to increase the timeout from the default 60 seconds.

**Comment by MaGeHome** [comment]
The Huawei Modbus is not the fastest. I cannot say exactly how long the query via node-red takes.
I think that the query takes about 5 seconds. I had already set the polling intervals to 5 seconds, and I had no problems.

The Modbus node in node-red has a client timeout of 5000 sec.
```
    {
        "id": "3eb6c7f3aa55b1c2",
        "type": "modbus-client",
        "name": "ModBus-TCP",
        "clienttype": "tcp",
        "bufferCommands": true,
        "stateLogEnabled": false,
        "queueLogEnabled": false,
        "failureLogEnabled": false,
        "tcpHost": "192.168.0.18",
        "tcpPort": "502",
        "tcpType": "DEFAULT",
        "serialPort": "/dev/ttyUSB",
        "serialType": "RTU-BUFFERD",
        "serialBaudrate": "9600",
        "serialDatabits": "8",
        "serialStopbits": "1",
        "serialParity": "none",
        "serialConnectionDelay": "100",
        "serialAsciiResponseStartDelimiter": "",
        "unit_id": "1",
        "commandDelay": "1",
        "clientTimeout": "5000",
        "reconnectOnTimeout": true,
        "reconnectTimeout": "2000",
        "parallelUnitIdsAllowed": true,
        "showErrors": true,
        "showWarnings": false,
        "showLogs": false
    }
```
Would it be possible to increase the timeout from 60 seconds as a test?

**Comment by MaGeHome** [comment]
> In case it just is a very slow operation: 1.0.6 adds a `--timeout` flag which you could use to increase the timeout from the default 60 seconds.

Wow, thank you very much.
I have set the timeout to 100 seconds. 
And also increased the query interval in node-red to 60 seconds.

Unfortunately, the error message still appears.

```
time="2024-11-19T23:31:45+01:00" level=info msg="creating target connection"
time="2024-11-19T23:31:46+01:00" level=info msg="new target connection: 172.19.0.2:43572 <-> 192.168.0.18:502"
time="2024-11-19T23:32:14+01:00" level=info msg="#23: 172.19.0.1:32972 <-> 172.19.0.2:1502"
time="2024-11-19T23:32:46+01:00" level=error msg="target connection: read tcp 172.19.0.2:43572->192.168.0.18:502: i/o timeout"
time="2024-11-19T23:32:46+01:00" level=error msg="failed to forward message, read tcp 172.19.0.2:43572->192.168.0.18:502: i/o timeout"
time="2024-11-19T23:32:46+01:00" level=info msg="Connected clients: 7"
time="2024-11-19T23:32:46+01:00" level=info msg="creating target connection"
time="2024-11-19T23:32:47+01:00" level=info msg="new target connection: 172.19.0.2:54020 <-> 192.168.0.18:502"
time="2024-11-19T23:33:14+01:00" level=info msg="#24: 172.19.0.1:40002 <-> 172.19.0.2:1502"
time="2024-11-19T23:33:47+01:00" level=error msg="target connection: read tcp 172.19.0.2:54020->192.168.0.18:502: i/o timeout"
time="2024-11-19T23:33:47+01:00" level=error msg="failed to forward message, read tcp 172.19.0.2:54020->192.168.0.18:502: i/o timeout"
```

**Comment by capi** [comment]
Can you change your inverters IP address? And only point the multiplexer to the new IP? This way we could rule out once and for all that something is concurrently accessing the inverter.

**Comment by IngmarStein** [comment]
v1.0.6 changes the log format to look like this:
```
^C2024/11/20 20:12:54 INFO closing server...
2024/11/20 20:12:54 INFO no more connections will be accepted
2024/11/20 20:12:54 INFO incoming connections closed
2024/11/20 20:12:54 INFO multiplexer server stopped gracefully
2024/11/20 20:12:54 INFO server is closed gracefully
```

Hence my question whether you updated the image _and_ recreated the container using the new image.

In `node-red_traffic.pcapng`, 192.168.0.29 (node-red) is talking modbus/TCP on port 502 with 192.168.0.18 (inverter).

In `multiplexer_traffic.pcapng`, 172.19.0.1 is talking modbus/TCP on port 1502 to 172.19.0.2 (multiplexer) and 172.169.0.2 is forwarding the requests to 192.168.0.18 on port 502. As requested earlier, could you please try `networking: host`?

**Comment by MaGeHome** [comment]
At Wireshark you can see, the inverter have only on connection.
![grafik](https://github.com/user-attachments/assets/5ffd4e3e-5f59-45e8-9b54-9123523e2145)

I recreated the container with
```
services:
  modbus-proxy:
    platform: linux/arm64
    image: ghcr.io/ingmarstein/tcp-multiplexer
    container_name: Modbus-Multiplexer
    ports:
      - "502:1502"
    network_mode: host
    command: [ "server", "-t", "192.168.0.18:502", "-l", "1502", "-p", "modbus", "-v" ]
    restart: always
    environment:
      TZ: Europe/Berlin
    hostname: Modbus_Container
    dns: 192.168.0.1
```
After that you can see, that i have no traffic at inverter.
![grafik](https://github.com/user-attachments/assets/05e7be1f-20bf-4893-8b96-7d02034b3753)

Then i connected node-red to the multiplexer host 127.0.1.1 at port 1502 an you can see the traffic in the file.
[multiplexer_host_traffic.zip](https://github.com/user-attachments/files/17835994/multiplexer_host_traffic.zip)
```
In the log it change nothing.
$ docker logs Modbus-Multiplexer
time="2024-11-20T20:38:37+01:00" level=info msg="#1: 192.168.0.29:56078 <-> 192.168.0.29:1502"
time="2024-11-20T20:38:37+01:00" level=info msg="Connected clients: 1"
time="2024-11-20T20:38:39+01:00" level=info msg="creating target connection"
time="2024-11-20T20:38:39+01:00" level=info msg="new target connection: 192.168.0.29:50026 <-> 192.168.0.18:502"
time="2024-11-20T20:38:48+01:00" level=info msg="#2: 192.168.0.29:44482 <-> 192.168.0.29:1502"
time="2024-11-20T20:38:58+01:00" level=info msg="#3: 192.168.0.29:40308 <-> 192.168.0.29:1502"
time="2024-11-20T20:39:08+01:00" level=info msg="#4: 192.168.0.29:35376 <-> 192.168.0.29:1502"
time="2024-11-20T20:39:18+01:00" level=info msg="#5: 192.168.0.29:37734 <-> 192.168.0.29:1502"
time="2024-11-20T20:39:28+01:00" level=info msg="#6: 192.168.0.29:34196 <-> 192.168.0.29:1502"
time="2024-11-20T20:39:29+01:00" level=info msg="closed: 192.168.0.29:34196 <-> 192.168.0.29:1502"
time="2024-11-20T20:39:39+01:00" level=error msg="target connection: read tcp 192.168.0.29:50026->192.168.0.18:502: i/o timeout"
time="2024-11-20T20:39:39+01:00" level=info msg="Connected clients: 2"
time="2024-11-20T20:39:39+01:00" level=info msg="creating target connection"
time="2024-11-20T20:39:39+01:00" level=error msg="failed to forward message, read tcp 192.168.0.29:50026->192.168.0.18:502: i/o timeout"
time="2024-11-20T20:39:40+01:00" level=info msg="new target connection: 192.168.0.29:52528 <-> 192.168.0.18:502"
time="2024-11-20T20:40:40+01:00" level=error msg="target connection: read tcp 192.168.0.29:52528->192.168.0.18:502: i/o timeout"
time="2024-11-20T20:40:40+01:00" level=info msg="Connected clients: 3"
time="2024-11-20T20:40:40+01:00" level=info msg="creating target connection"
time="2024-11-20T20:40:40+01:00" level=error msg="failed to forward message, read tcp 192.168.0.29:52528->192.168.0.18:502: i/o timeout"
time="2024-11-20T20:40:41+01:00" level=info msg="new target connection: 192.168.0.29:53280 <-> 192.168.0.18:502"
time="2024-11-20T20:40:58+01:00" level=info msg="#7: 127.0.0.1:43778 <-> 127.0.1.1:1502"
time="2024-11-20T20:41:08+01:00" level=info msg="#8: 127.0.0.1:35426 <-> 127.0.1.1:1502"
time="2024-11-20T20:41:18+01:00" level=info msg="#9: 127.0.0.1:55334 <-> 127.0.1.1:1502"
time="2024-11-20T20:41:28+01:00" level=info msg="#10: 127.0.0.1:54364 <-> 127.0.1.1:1502"
time="2024-11-20T20:41:38+01:00" level=info msg="#11: 127.0.0.1:41924 <-> 127.0.1.1:1502"
time="2024-11-20T20:41:41+01:00" level=error msg="target connection: read tcp 192.168.0.29:53280->192.168.0.18:502: i/o timeout"
time="2024-11-20T20:41:41+01:00" level=error msg="failed to forward message, read tcp 192.168.0.29:53280->192.168.0.18:502: i/o timeout"
time="2024-11-20T20:41:41+01:00" level=info msg="Connected clients: 4"
time="2024-11-20T20:41:41+01:00" level=info msg="creating target connection"
time="2024-11-20T20:41:42+01:00" level=info msg="new target connection: 192.168.0.29:50844 <-> 192.168.0.18:502"
time="2024-11-20T20:41:48+01:00" level=info msg="#12: 127.0.0.1:53402 <-> 127.0.1.1:1502"
time="2024-11-20T20:41:58+01:00" level=info msg="#13: 127.0.0.1:41748 <-> 127.0.1.1:1502"
time="2024-11-20T20:42:08+01:00" level=info msg="#14: 127.0.0.1:39386 <-> 127.0.1.1:1502"
time="2024-11-20T20:42:18+01:00" level=info msg="#15: 127.0.0.1:39642 <-> 127.0.1.1:1502"
time="2024-11-20T20:42:28+01:00" level=info msg="#16: 127.0.0.1:38738 <-> 127.0.1.1:1502"
time="2024-11-20T20:42:38+01:00" level=info msg="#17: 127.0.0.1:48308 <-> 127.0.1.1:1502"
time="2024-11-20T20:42:42+01:00" level=error msg="target connection: read tcp 192.168.0.29:50844->192.168.0.18:502: i/o timeout"
```

**Comment by IngmarStein** [comment]
- "I recreated the container with […]": did you run `docker compose pull` and `docker compose up -d` to recreate the container using the new image version?
- "I connected node-red to the multiplexer host 127.0.1.1 at port 1502": but your compose file contains `502:1502`, so you should connect to port 502, not 1502 (it's HOST_PORT:CONTAINER_PORT)
- Did you try `networking: host`?

**Comment by IngmarStein** [comment]
The captures show identical requests being sent to the inverter (e.g. frame 8474 in multiplexer_host_traffic and frame 179 in node-red_traffic). They differ only in sequence numbers and checksums.

Maybe try running tcp-multiplexer as a native binary instead of a container to rule out Docker networking altogether? I'm running out of options and am tempted to give up at this point because it seems to be working fine for other people.

**Comment by MaGeHome** [comment]
I already have a guilty conscience because I'm taking up so much of your time with my problem.
I'll try it with tcp-multiplexer as a native binary.
Thank you very much for taking so much time for my problem, even though we didn't find a solution.
I think we can close the case.

**Comment by IngmarStein** [comment]
@MaGeHome if you'd like, you could give v1.0.7 with `--delay 2` a try (see #10).

**Comment by MaGeHome** [comment]
Thanks for your support!
Unfortunately, it's the same result.
```
services:
  modbus-proxy:
    image: ghcr.io/ingmarstein/tcp-multiplexer:latest
    container_name: Modbus-Multiplexer
    ports:
      - "502:502"
    command: [ "server", "-t", "192.168.0.18:502", "-l", "502", "-p", "modbus", "-v", "timeout 65", "delay 2" ]
    restart: always
```
```
time="2024-12-02T21:01:03+01:00" level=info msg="creating target connection"
time="2024-12-02T21:01:04+01:00" level=info msg="new target connection: 172.19.0.2:51564 <-> 192.168.0.18:502"
time="2024-12-02T21:01:07+01:00" level=info msg="#1: 192.168.0.29:45562 <-> 172.19.0.2:502"
time="2024-12-02T21:01:12+01:00" level=info msg="#2: 192.168.0.29:49506 <-> 172.19.0.2:502"
time="2024-12-02T21:01:19+01:00" level=info msg="#3: 192.168.0.29:46182 <-> 172.19.0.2:502"
time="2024-12-02T21:01:31+01:00" level=info msg="#4: 192.168.0.29:54840 <-> 172.19.0.2:502"
time="2024-12-02T21:02:04+01:00" level=error msg="target connection: read tcp 172.19.0.2:51564->192.168.0.18:502: i/o timeout"
time="2024-12-02T21:02:04+01:00" level=error msg="failed to forward message, read tcp 172.19.0.2:51564->192.168.0.18:502: i/o timeout"
```
With `tiagocoutinho/modbus-proxy` it works

**Comment by MaGeHome** [comment]
Thanks for your notice. 
You are right. your example is correct for the array form.

But the Modbus multiplexer has problems with the flags  "delay" and "timeout". Both with "--" and with "-". I tested via console.
That's why I tried it in the array as above
```
sudo docker run ghcr.io/ingmarstein/tcp-multiplexer:latest server -t  192.168.0.18:502 -l 502 -p modbus -v --delay 2 --timeout 65
````
```
Error: unknown flag: --delay
unknown flag: --delay
Usage:
  tcp-multiplexer server [flags]
Flags:
  -p, --applicationProtocol string   multiplexer will parse to message echo/http/iso8583/modbus (default "echo")
  -h, --help                         help for server
  -l, --listen string                multiplexer will listen on (default "8000")
  -t, --targetServer string          multiplexer will forward message to (default "127.0.0.1:1234")
Global Flags:
  -d, --debug     debug log
  -v, --verbose   verbose log
```
```
sudo docker run ghcr.io/ingmarstein/tcp-multiplexer:latest server -t  192.168.0.18:502 -l 502 -p modbus -v -delay 2 -timeout 65
````
```
Error: unknown shorthand flag: 'e' in -elay
Usage:
  tcp multiplexer server [flags]
Flags:
  -p, --applicationProtocol string   multiplexer will parse to message echo/http/iso8583/modbus (default "echo")
  -h, --help                         help for server
  -l, --listen string                multiplexer will listen on (default "8000")
  -t, --targetServer string          multiplexer will forward message to (default "127.0.0.1:1234")
Global Flags:
  -d, --debug     debug log
  -v, --verbose   verbose log
```

**Comment by capi** [comment]
Are you sure you pulled "latest" recently? Try with `docker run --rm -it ghcr.io/ingmarstein/tcp-multiplexer:1.0.7-amd64` to be sure you are actually running the 1.0.7 version. Without pulling "latest" will stay at whatever the image was when you first pulled it.

![image](https://github.com/user-attachments/assets/9aa1a8ee-6ae7-4914-abb5-243bca9019a6)

**Comment by IngmarStein** [comment]
@MaGeHome as mentioned in https://github.com/IngmarStein/tcp-multiplexer/issues/9#issuecomment-2489371251, I believe you‘re just recreating new containers using the first image version you ever pulled. The usage description confirms that. Please try using a tagged version as suggested by @capi.

**Comment by MaGeHome** [comment]
You guys are great. 

With my wrong assumption that the latest image is loaded with pull image:latest, the problem probably sat in front of the computer.

Now with the image 1.07 and the flag delay 2S, the modbus multiplexer works perfectly.

Thanks again for your help.

**Comment by IngmarStein** [comment]
Good to hear that! Thanks for closing the loop.
